#######################################################################
# Check the Rails Evironment Variables are sourced for the deploy user
#######################################################################
- name: "Environment | Update /etc/default/dvmtn_shared"
  template: src=deploy_shared_env.j2 dest=/etc/default/dvmtn_shared owner=root group={{deploy_user}} mode=0440
  when: dvmtn_shared_env is defined

- name: "Environment | Update /etc/default/{{item}}"
  template: src=deploy_app_env.j2 dest=/etc/default/{{item.key}} owner=root group={{deploy_user}} mode=0440
  with_dict: "{{ dvmtn_app_env }}"

- name: Environment | Add environment variables from system config to .profile
  lineinfile: "dest=/home/{{deploy_user}}/.profile state=present line='[[ -f /etc/default/{{item}} ]] && . /etc/default/{{app_name}}'"
  with_dict: "{{ dvmtn_app_env }}"


- name: Environment | Add environment variables from system config to .bash_profile
  lineinfile: dest=/home/{{deploy_user}}/.bash_profile
              create=yes
              owner={{deploy_user}}
              group={{deploy_user}}
              mode=0600
              line='if [ -f /etc/default/{{item}} ] ; then source /etc/default/{{item}}; fi'
  with_dict: "{{ dvmtn_app_env }}"

- name: Environment | Ensure environment variables are loaded during non-interactive shells
  lineinfile: dest=/home/{{deploy_user}}/.bashrc
              create=yes
              owner={{deploy_user}}
              group={{deploy_user}}
              mode=0644
              insertbefore=BOF
              line='if [ -f /etc/default/{{item}} ] ; then source /etc/default/{{item}}; fi'
  with_dict: "{{ dvmtn_app_env }}"

